import json, glob

BANKS = sorted(glob.glob('solutions_*.json'))
master = {}
src = {}
for f in BANKS:
    try:
        d = json.load(open(f, encoding='utf-8'))
    except Exception as e:
        print('SKIP (bad json)', f, e)
        continue
    for k, v in d.items():
        if k not in master:
            master[k] = v
            src[k] = f
        elif len(v) > len(master[k]):
            master[k] = v
            src[k] = f

json.dump(master, open('SOLUTIONS_MASTER.json', 'w', encoding='utf-8'), indent=1, sort_keys=True)

out = []
out.append('# LEETCODE SOLUTIONS ARCHIVE')
out.append('')
out.append('Auto-generated by build_archive.py - do NOT hand-edit, re-run the script instead.')
out.append('')
out.append('Unique solutions: ' + str(len(master)))
out.append('Source bank files: ' + str(len(BANKS)))
out.append('')
out.append('## Bank inventory')
out.append('')
for f in BANKS:
    try:
        n = len(json.load(open(f, encoding='utf-8')))
    except Exception:
        n = 0
    out.append('- ' + f + '  (' + str(n) + ' entries)')
out.append('')
out.append('## Solutions A-Z')
out.append('')
for slug in sorted(master):
    out.append('### ' + slug)
    out.append('')
    out.append('_source bank: ' + src[slug] + '_')
    out.append('')
    out.append('```python')
    out.append(master[slug])
    out.append('```')
    out.append('')
open('SOLUTIONS.md', 'w', encoding='utf-8').write('\n'.join(out))

idx = []
idx.append('# SOLUTIONS INDEX')
idx.append('')
idx.append('Auto-generated by build_archive.py - re-run the script to refresh.')
idx.append('')
idx.append('Unique solutions across all banks: **' + str(len(master)) + '**')
idx.append('')
idx.append('| bank file | entries | unique to this bank |')
idx.append('|---|---|---|')
for f in BANKS:
    try:
        n = len(json.load(open(f, encoding='utf-8')))
    except Exception:
        n = 0
    own = sum(1 for k in src if src[k] == f)
    idx.append('| ' + f + ' | ' + str(n) + ' | ' + str(own) + ' |')
idx.append('')
idx.append('Full per-problem listing: see `SOLUTIONS.md` (or `SOLUTIONS_MASTER.json` for')
idx.append('machine use). How to run a bank: see `START-HERE.md`.')
idx.append('')
open('SOLUTIONS_INDEX.md', 'w', encoding='utf-8').write('\n'.join(idx))
print('SOLUTIONS_INDEX.md written')
print('SOLUTIONS_MASTER.json unique:', len(master))
print('SOLUTIONS.md lines:', len(out))